In [27]:
import numpy as np

In [28]:
def relu(x):
    return np.maximum(0, x)

In [29]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [30]:
def softmax(x):
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

In [31]:
#輸入層的參數
x = np.array([5.0 , 6.0 , 2.0 , 1.0 , 3.0 , 8.0])
x.shape

(6,)

In [32]:
#第一隱藏層：五個神經元

In [33]:
#第一隱藏層的權重
w1 = np.array([[1.5,2.0,0.5,5.5,3.0],
               [1.0,3.0,1.5,5.0,3.5],
               [0.5,2.5,2.0,5.5,3.0],
               [1.0,2.5,0.0,5.0,2.0],
               [1.5,3.5,0.5,3.0,1.5],
               [0.5,1.5,4.5,1.0,1.0]])
w1.shape

(6, 5)

In [34]:
#偏置
b1 = np.array([2.0,2.5,1.0,4.5,2.0])
b1.shape

(5,)

In [35]:
#第一隱藏層加權
z1 = np.dot(x,w1)+b1
print(z1)
print(z1.shape)

[26.  60.5 54.  95.  58.5]
(5,)


In [36]:
#使用激發函數
h1 = relu(z1)
print(h1)
print(h1.shape)

[26.  60.5 54.  95.  58.5]
(5,)


In [37]:
#第二隱藏層：四個神經元

In [38]:
#第二隱藏層的權重
w2 = np.array([[1.5,0.5,0.5,-1.5],
               [-2.5,0.0,2.5,2.0],
               [-1.5,-1.0,3.0,-2.5],
               [2.5,2.5,-1.0,1.0],
               [-1.5,4.5,1.5,-1.5]])
w2.shape

(5, 4)

In [39]:
#偏置
b2 = np.array([2.5,1.0,2.5,1.0])
b2.shape

(4,)

In [40]:
#第二隱藏層加權
z2 = np.dot(h1,w2)+b2
print(z2)
print(z2.shape)

[-41.   460.75 321.5  -44.75]
(4,)


In [41]:
#使用激發函數
h2 = relu(z2)
print(h2)
print(h2.shape)

[  0.   460.75 321.5    0.  ]
(4,)


In [42]:
#第三隱藏層：四個神經元

In [43]:
#第三隱藏層的權重
w3 = np.array([[-0.5,0.5,1.5,1.5],
               [0.5,2.0,2.5,1.0],
               [0.5,2.0,1.0,1.5],
               [-0.5,1.5,0.5,1.5]])
w3.shape

(4, 4)

In [44]:
#偏置
b3 = np.array([0.5,2.0,1.5,2.0])
b3.shape

(4,)

In [45]:
#第三隱藏層加權
z3 = np.dot(h2,w3)+b3
print(z3)
print(z3.shape)

[ 391.625 1566.5   1474.875  945.   ]
(4,)


In [46]:
#使用激發函數
h3 = sigmoid(z3)
print(h3)
print(h3.shape)

[1. 1. 1. 1.]
(4,)


In [47]:
#輸出層：三個神經元

In [48]:
#輸出層的權重
w_out = np.array([[1.5,1.0,0.5],
                  [0.5,1.0,1.5],
                  [1.0,1.5,1.5],
                  [2.0,1.5,0.5]])
w_out.shape

(4, 3)

In [49]:
#偏置
b_out = np.array([1.0,2.0,1.5])
b_out.shape

(3,)

In [50]:
#輸出層加權
z_out = np.dot(h3,w_out)+b_out
print(z_out)
print(z_out.shape)

[6.  7.  5.5]
(3,)


In [51]:
#使用激發函數
y_hat = softmax(z_out)
print(y_hat)
print(y_hat.shape)

[0.2312239  0.62853172 0.14024438]
(3,)
