In [1]:
import numpy as np
import gradio as gr

In [2]:
def relu(x):
    return np.maximum(0, x)
def sigmoid(x):
    return 1/(1+np.exp(-x))
def softmax(x):
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

In [3]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)

    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + 1e-7)) / batch_size

In [7]:
X=np.array([[1.5, 1.5], [0.5, 1.0], [0.8, 0.3],[1.5, 0.4],[1.0, 1.3]])
t=np.array([[1, 1, 0], [0, 1, 0], [1, 1, 1],[1, 0, 1],[0, 1, 1]]) #標籤

In [8]:
X.shape

(5, 2)

In [9]:
X

array([[1.5, 1.5],
       [0.5, 1. ],
       [0.8, 0.3],
       [1.5, 0.4],
       [1. , 1.3]])

In [10]:
#第一隱藏層的權重
w1 = np.array([[1.5,2.0,0.5,5.5,3.0],
               [0.5,1.5,4.5,1.0,1.0]])
w1.shape

(2, 5)

In [11]:
#偏置
b1 = np.array([2.0,2.5,1.0,4.5,2.0])
b1.shape

(5,)

In [13]:
#第一隱藏層加權
z1 = np.dot(X,w1)+b1
print(z1)
print(z1.shape)

[[ 5.    7.75  8.5  14.25  8.  ]
 [ 3.25  5.    5.75  8.25  4.5 ]
 [ 3.35  4.55  2.75  9.2   4.7 ]
 [ 4.45  6.1   3.55 13.15  6.9 ]
 [ 4.15  6.45  7.35 11.3   6.3 ]]
(5, 5)


In [14]:
#使用激發函數
h1 = relu(z1)
print(h1)
print(h1.shape)

[[ 5.    7.75  8.5  14.25  8.  ]
 [ 3.25  5.    5.75  8.25  4.5 ]
 [ 3.35  4.55  2.75  9.2   4.7 ]
 [ 4.45  6.1   3.55 13.15  6.9 ]
 [ 4.15  6.45  7.35 11.3   6.3 ]]
(5, 5)


In [15]:
#第二隱藏層的權重
w2 = np.array([[1.5,0.5,0.5,-1.5],
               [-2.5,0.0,2.5,2.0],
               [-1.5,-1.0,3.0,-2.5],
               [2.5,2.5,-1.0,1.0],
               [-1.5,4.5,1.5,-1.5]])
w2.shape

(5, 4)

In [16]:
#偏置
b2 = np.array([2.5,1.0,2.5,1.0])
b2.shape

(4,)

In [17]:
#第二隱藏層加權
z2 = np.dot(h1,w2)+b2
print(z2)
print(z2.shape)

[[  1.5    66.625  47.625 -10.   ]
 [  0.125  37.75   32.375  -6.75 ]
 [  7.975  44.075  21.65    0.35 ]
 [ 11.125  63.6    27.825   0.45 ]
 [  0.375  52.325  40.9    -8.85 ]]
(5, 4)


In [18]:
#使用激發函數
h2 = relu(z2)
print(h2)
print(h2.shape)

[[ 1.5   66.625 47.625  0.   ]
 [ 0.125 37.75  32.375  0.   ]
 [ 7.975 44.075 21.65   0.35 ]
 [11.125 63.6   27.825  0.45 ]
 [ 0.375 52.325 40.9    0.   ]]
(5, 4)


In [19]:
#第三隱藏層的權重
w3 = np.array([[-0.5,0.5,1.5,1.5],
               [0.5,2.0,2.5,1.0],
               [0.5,2.0,1.0,1.5],
               [-0.5,1.5,0.5,1.5]])
w3.shape

(4, 4)

In [20]:
#偏置
b3 = np.array([0.5,2.0,1.5,2.0])
b3.shape

(4,)

In [21]:
#第三隱藏層加權
z3 = np.dot(h2,w3)+b3
print(z3)
print(z3.shape)

[[ 56.875  231.25   217.9375 142.3125]
 [ 35.5    142.3125 128.4375  88.5   ]
 [ 29.2    137.9625 145.475   91.0375]
 [ 40.425  191.0875 205.2375 124.7   ]
 [ 46.925  188.6375 173.775  116.2375]]
(5, 4)


In [22]:
#使用激發函數
h3 = sigmoid(z3)
print(h3)
print(h3.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(5, 4)


In [23]:
#輸出層的權重
w_out = np.array([[1.5,1.0,0.5],
                  [0.5,1.0,1.5],
                  [1.0,1.5,1.5],
                  [2.0,1.5,0.5]])
w_out.shape

(4, 3)

In [24]:
#偏置
b_out = np.array([1.0,2.0,1.5])
b_out.shape

(3,)

In [25]:
#輸出層加權
z_out = np.dot(h3,w_out)+b_out
print(z_out)
print(z_out.shape)

[[6.  7.  5.5]
 [6.  7.  5.5]
 [6.  7.  5.5]
 [6.  7.  5.5]
 [6.  7.  5.5]]
(5, 3)


In [26]:
#使用激發函數
y_hat = softmax(z_out)
print(y_hat)
print(y_hat.shape)

[[0.04624478 0.12570634 0.02804888]
 [0.04624478 0.12570634 0.02804888]
 [0.04624478 0.12570634 0.02804888]
 [0.04624478 0.12570634 0.02804888]
 [0.04624478 0.12570634 0.02804888]]
(5, 3)
