第二題

In [1]:
import numpy as np

In [2]:
h0 = np.array([0, 0, 0, 0])
h0

array([0, 0, 0, 0])

In [3]:
X = np.random.randint(0, 10, size=(3,3))
X

array([[4, 0, 1],
       [3, 9, 1],
       [3, 4, 4]])

In [4]:
x1 = X[0]
x2 = X[1]
x3 = X[2]

In [5]:
x1, x2, x3

(array([4, 0, 1]), array([3, 9, 1]), array([3, 4, 4]))

In [6]:
Wx = np.array([[1, -1, 0, 0.5], [2, 0, -1, 3], [1.5, 1, 2, -1]])
Wh = np.array([[1.2, 0.3, 0.1, 0.6], [0.4, 2, 1, 0.1], [0.2, 1.3, 0.7, 1.6], [2.4, 0.2, 0.1, 0.7]])
b = np.array([0.3, 0.8, 0.5, 0.2])

In [7]:
# 給x1, h0
z1 = np.dot(x1, Wx) + np.dot(h0, Wh) + b
z1

array([ 5.8, -2.2,  2.5,  1.2])

In [8]:

h1 = np.tanh(z1)
h1

array([ 0.99998167, -0.97574313,  0.9866143 ,  0.83365461])

In [10]:
# 給x2, h1
z2 = np.dot(x2, Wx) + np.dot(h1, Wh) + b
z2


array([25.80777467, -1.40216225, -6.60174949, 30.36455579])

In [11]:
h2 = np.tanh(z2)
h2

array([ 1.        , -0.88581813, -0.99999631,  1.        ])

In [12]:
# 給x3, h2
z3 = np.dot(x3, Wx) + np.dot(h2, Wh) + b
z3

array([20.34567349, -0.77163147,  3.11418445,  9.31142409])

In [13]:
h3 = np.tanh(z3)
h3

array([ 1.        , -0.64787712,  0.99606243,  0.99999998])

第三題

In [9]:
S3 = np.array([2, 5, 3, 1])
S3

array([2, 5, 3, 1])

In [14]:
e1 = np.dot(S3, h1)
e2 = np.dot(S3, h2)
e3 = np.dot(S3, h3)
e = np.array([e1, e2, e3])
e

array([ 0.91474519, -4.42907959,  2.7488017 ])

In [15]:
def softmax_0(x): # x是一個向量
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

In [16]:
def softmax(x): # x 可以是一個向量或矩陣(多個向量)
    x = x - np.max(x, axis=-1, keepdims=True)
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)


In [17]:
alpha = softmax(e)
alpha

array([1.37665134e-01, 6.57703798e-04, 8.61677162e-01])

In [18]:
h = np.array([h1, h2, h3])


In [19]:
c3 = np.dot(alpha, h)
c3

array([ 0.99999748, -0.69316933,  0.99344894,  0.97710003])

第4題

In [20]:
WQ = np.array([[0, 0, 1], [1, 0, 0], [0, 0, 1]])
WK = np.array([[1, 0, 1], [0, 1, 1], [0, 1, 0]])
WV = np.array([[0, 2, 1], [1, 0, 3], [1, 0, 1]])

In [21]:
Q = np.dot(X, WQ)
Q

array([[0, 0, 5],
       [9, 0, 4],
       [4, 0, 7]])

In [22]:
K = np.dot(X, WK)
K

array([[ 4,  1,  4],
       [ 3, 10, 12],
       [ 3,  8,  7]])

In [23]:
V = np.dot(X, WV)
V

array([[ 1,  8,  5],
       [10,  6, 31],
       [ 8,  6, 19]])

In [24]:
def Attention (Q, K, V):
  d = 3
  return np.dot(softmax(np.dot(Q, K.T) / np.sqrt(d)), V)

In [25]:
att = Attention(Q, K, V)
att

array([[ 9.99999892,  6.        , 30.99999353],
       [ 9.99996528,  6.00000342, 30.99983956],
       [10.        ,  6.        , 30.99999998]])

In [26]:
c1 = att[0]
c1

array([ 9.99999892,  6.        , 30.99999353])

In [27]:
c2 = att[1]
c2

array([ 9.99996528,  6.00000342, 30.99983956])

In [28]:
c3 = att[2]
c3

array([10.        ,  6.        , 30.99999998])